"""add expenses table

Revision ID: 04f3b64dc3e3
Revises: a7ed9b92320e
Create Date: 2026-04-17 18:43:33.282422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f3b64dc3e3'
down_revision = 'a7ed9b92320e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_sales_transaction_id'), ['transaction_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_transaction_id'))
        batch_op.drop_column('transaction_id')

    op.drop_table('expenses')
    # ### end Alembic commands ###
