"""add wholesale price and carton qty to products

Revision ID: 0a3b6407b758
Revises: 16d6fb7bf010
Create Date: 2026-06-16 10:59:45.232098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3b6407b758'
down_revision = '16d6fb7bf010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wholesale_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('carton_qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('carton_qty')
        batch_op.drop_column('wholesale_price')

    # ### end Alembic commands ###
