"""change sale_item quantity to float

Revision ID: 15676407d0b5
Revises: f49fe4f3cdf0
Create Date: 2026-04-18 13:31:36.822070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15676407d0b5'
down_revision = 'f49fe4f3cdf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
