"""add sold_loose to products

Revision ID: 525278c514ae
Revises: 15676407d0b5
Create Date: 2026-04-18 13:49:45.470009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525278c514ae'
down_revision = '15676407d0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_loose', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('sold_loose')

    # ### end Alembic commands ###
