"""add cash and mpesa amount columns to sales

Revision ID: 8f240397dba8
Revises: 9786d97c9d0c
Create Date: 2026-07-06 21:28:22.570576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f240397dba8'
down_revision = '9786d97c9d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('mpesa_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('mpesa_amount')
        batch_op.drop_column('cash_amount')

    # ### end Alembic commands ###
