"""add customer name fields to mpesa_transactions

Revision ID: 92aff41a54e7
Revises: a0b5cae55194
Create Date: 2026-04-20 10:31:16.268876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aff41a54e7'
down_revision = 'a0b5cae55194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_middle_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sender_last_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_column('sender_last_name')
        batch_op.drop_column('sender_middle_name')
        batch_op.drop_column('sender_first_name')

    # ### end Alembic commands ###
