"""add low_stock_threshold to products

Revision ID: 99cc84549c5f
Revises: ca4c0ad3e6c3
Create Date: 2026-09-23 00:02:32.368428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99cc84549c5f'
down_revision = 'ca4c0ad3e6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('low_stock_threshold')

    # ### end Alembic commands ###
