"""add shop_settings table

Revision ID: ca4c0ad3e6c3
Revises: 8f240397dba8
Create Date: 2026-07-13 10:22:59.601759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4c0ad3e6c3'
down_revision = '8f240397dba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('shop_tagline', sa.String(length=200), nullable=True),
    sa.Column('shop_phone', sa.String(length=20), nullable=True),
    sa.Column('shop_address', sa.String(length=200), nullable=True),
    sa.Column('receipt_footer', sa.String(length=300), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_settings')
    # ### end Alembic commands ###
