"""add department to expenses

Revision ID: fd9317d3c4ad
Revises: ad0771814c4c
Create Date: 2026-04-27 23:31:08.045447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9317d3c4ad'
down_revision = 'ad0771814c4c'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1 — add column as nullable first
    op.add_column('expenses',
        sa.Column('department', sa.String(20), nullable=True)
    )
    # Step 2 — fill existing rows with 'shop'
    op.execute("UPDATE expenses SET department = 'shop' WHERE department IS NULL")
    # Step 3 — now make it NOT NULL
    op.alter_column('expenses', 'department', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('department')

    # ### end Alembic commands ###
